version: '3.8'

services:
  playwright-tests:
    image: mcr.microsoft.com/playwright/dotnet:v1.51.0-noble
    working_dir: /app
    volumes:
      - .:/app 
    environment:
      - DOTNET_ENVIRONMENT=Development
    command:
      - bash
      - -c
      - |
        cd /app
        dotnet restore
        dotnet build --no-restore
        dotnet test --no-build
    depends_on: []
    network_mode: "host"